### PR TITLE
updating README.md to improve documentation on oath verification

### PR DESCRIPTION
**Pull request by dencold**
- now includes step-by-step instructions and screenshots.

### CODE REVIEW

**Comment by duqcyxwd** [comment]
I have a problem when I try to install SublimeEvernote.  I am using ST3 portalable Version.  This is the error: 

```
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
reloading plugin SublimeEvernote.html
reloading plugin SublimeEvernote.sublime_evernote
Traceback (most recent call last):
File "C:\My Program\Sublime Text Build 3047 x64\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
File "C:\My Program\Sublime Text Build 3047 x64\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
File "sublime_evernote in C:\My Program\Sublime Text Build 3047 x64\Data\Installed Packages\SublimeEvernote.sublime-package", line 41, in <module>
ImportError: No module named 'evernote'
```

I hope you can help me with it.

**Comment by dencold** [comment]
Hi @duqcyxwd, I'm still on sublime 2 myself, so I don't think I'll be much help here. It looks like the plugin is looking for the [evernote library](https://pypi.python.org/pypi/evernote/1.25.0) but can't find it and throws the exception you are seeing. I'm not sure how well ST3 is supported in SublimeEvernote as I'm not the author of the package.

Also, if you want help, it's best to put it on the [issue tracker](https://github.com/jamiesun/SublimeEvernote/issues) of the actual library. This is just a pull request.

**Comment by duqcyxwd** [comment]
@dencold Thanks for your reply. I found someone already pull a issue about sublime text 3

**Comment by dencold** [comment]
Thanks so much for merging in the PR @jamiesun.

**Pull request merged**
